import { evaluate5Cards, evaluate6Cards, evaluate7Cards } from "./core/evaluator";
import { getCardCodes, getBoardCodes } from "./utils/card";
import { getHandRank, HandRank, HAND_RANK_DESCRIPTIONS } from "./models/hand-rank";

// Export Constants and Enums for consumers
export { HandRank, HAND_RANK_DESCRIPTIONS } from "./models/hand-rank";
export { stringifyCardCode, getCardCode, getCardCodes } from "./utils/card";

/**
 * Primary entry point.
 * Evaluates 5, 6, or 7 card integer codes.
 * Returns a strength score (lower is better).
 *
 * @param codes Array of card integers (e.g. generated by getCardCode)
 */
export function evaluate(codes: number[]): number {
  const len = codes.length;
  if (len === 7) return evaluate7Cards(codes);
  if (len === 6) return evaluate6Cards(codes);
  if (len === 5) return evaluate5Cards(codes);

  throw new Error(`Evaluator requires 5, 6, or 7 cards. Received ${len}.`);
}

/**
 * Evaluates an array of card strings (e.g. ['As', 'Kd', ...]).
 * Slightly slower than `evaluate` due to parsing overhead.
 */
export function evaluateStrings(cards: string[]): number {
  return evaluate(getCardCodes(cards));
}

/**
 * Evaluates a board string (e.g. "As Kd Qh ...").
 */
export function evaluateBoard(board: string): number {
  return evaluate(getBoardCodes(board));
}

/**
 * Returns the HandRank (enum 0-8) for a given set of card integers.
 * Useful for categorizing hands (e.g. "Full House").
 */
export function rank(codes: number[]): HandRank {
  return getHandRank(evaluate(codes));
}

/**
 * Returns the HandRank (enum 0-8) for a given board string.
 */
export function rankBoard(board: string): HandRank {
  return getHandRank(evaluateBoard(board));
}

/**
 * Returns the human-readable name of the hand rank (e.g. "Straight Flush").
 */
export function rankDescription(rank: HandRank): string {
  return HAND_RANK_DESCRIPTIONS[rank];
}
