// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load appropriate env file based on NODE_ENV
if (process.env.NODE_ENV === "test") {
  config({ path: ".env.test" });
} else {
  config();
}

// Use DATABASE_URL from environment, fallback to dev database
const databaseUrl = process.env.DATABASE_URL || "file:../.runtime/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
