/**
 * export-schema.mjs — Build-time helper
 *
 * Creates a throw-away SQLite database, pushes the Prisma schema into it,
 * then exports the DDL (tables + indexes) as idempotent SQL to
 * prisma/schema.sql.  That file is copied into the production image so the
 * runtime can bootstrap a fresh SQLite database without the Prisma CLI.
 *
 * Prerequisites (available at build time):
 *   - prisma CLI (root devDependency)
 *   - better-sqlite3 (rebuilt earlier in the Dockerfile)
 *
 * Usage:  node scripts/export-schema.mjs
 */

import { execSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import Database from "better-sqlite3";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageDir = resolve(__dirname, "..");

// ---------------------------------------------------------------------------
// 1. Create a throw-away directory + SQLite database
// ---------------------------------------------------------------------------
const tmpDir = mkdtempSync(join(tmpdir(), "pokertools-export-"));
const dbPath = join(tmpDir, "export.db");
const dbUrl = `file:${dbPath}`;

// ---------------------------------------------------------------------------
// 2. Push the Prisma schema into the throw-away DB
// ---------------------------------------------------------------------------
console.log("--- Creating throw-away database with prisma db push ---");
execSync("npx prisma db push --accept-data-loss", {
  cwd: packageDir,
  env: { ...process.env, DATABASE_URL: dbUrl },
  stdio: "inherit",
});

// ---------------------------------------------------------------------------
// 3. Extract DDL from sqlite_master
// ---------------------------------------------------------------------------
console.log("--- Extracting DDL from throw-away database ---");
const db = new Database(dbPath);

// Get all tables, indexes, triggers (type IN table, index, trigger).
// sqlite_master.sql contains the original CREATE statement.
const rows = db
  .prepare(
    `SELECT type, name, sql FROM sqlite_master
     WHERE sql IS NOT NULL
       AND type IN ('table', 'index', 'trigger')
       AND name NOT LIKE 'sqlite_%'
      ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'index' THEN 2 WHEN 'trigger' THEN 3 END, name`,
  )
  .all();

const lines = [
  "-- =============================================================================",
  "-- schema.sql — Auto-generated by export-schema.mjs",
  "--",
  "-- Idempotent DDL for the PokerTools SQLite database.  Safe to execute on an",
  "-- empty database (every statement uses IF NOT EXISTS where applicable).",
  "-- =============================================================================",
  "",
  "PRAGMA foreign_keys=ON;",
  "",
];

for (const { type, sql } of rows) {
  // If the raw SQL already includes IF NOT EXISTS for tables, use it as-is.
  // For indexes, SQLite supports CREATE [UNIQUE] INDEX IF NOT EXISTS since 3.26.0,
  // but Prisma currently emits bare CREATE INDEX / CREATE UNIQUE INDEX.
  // We rewrite those so the script is trivially re-runnable.
  let statement = sql.trim();

  if (type === "table") {
    // CREATE TABLE "foo" ... -> CREATE TABLE IF NOT EXISTS "foo" ...
    // sqlite_master stores the raw SQL without IF NOT EXISTS, but we need
    // idempotent statements for runtime bootstrap.
    statement = statement.replace(
      /^CREATE TABLE "/,
      'CREATE TABLE IF NOT EXISTS "',
    );
  } else if (type === "index" && !/IF NOT EXISTS/i.test(statement)) {
    // CREATE UNIQUE INDEX "foo" ... -> CREATE UNIQUE INDEX IF NOT EXISTS "foo" ...
    statement = statement.replace(
      /^CREATE (UNIQUE )?INDEX /,
      "CREATE $1INDEX IF NOT EXISTS ",
    );
  }

  lines.push(statement + ";");
  lines.push("");
}

db.close();

// ---------------------------------------------------------------------------
// 4. Write prisma/schema.sql
// ---------------------------------------------------------------------------
const outPath = resolve(packageDir, "prisma", "schema.sql");
writeFileSync(outPath, lines.join("\n"), "utf-8");
console.log(`--- Wrote schema.sql (${lines.length} lines) to ${outPath} ---`);

// Clean up throw-away directory
rmSync(tmpDir, { recursive: true, force: true });
console.log("--- Cleaned up throw-away database ---");
